# Generated by Django 4.2.16 on 2024-11-21 18:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_cartitem_shopping_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'продукт в корзине', 'verbose_name_plural': 'Продукты в корзинах'},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_price',
            field=models.FloatField(null=True, verbose_name='Цена продукта'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_quantity',
            field=models.PositiveSmallIntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество продукта'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='shopping_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.shoppingcart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='total_price',
            field=models.FloatField(null=True, verbose_name='Суммарная цена продуктов'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='total_quantity',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Суммарное количество продуктов'),
        ),
    ]
