# Generated by Django 4.2.16 on 2024-11-24 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productimage_options_alter_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='total_quantity',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_price',
            field=models.FloatField(default=0, verbose_name='Цена продуктов'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_quantity',
            field=models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена'),
        ),
    ]
